"""add tag and todo_tag relation

Revision ID: a85c1e7fa0e1
Revises: 4c0aeefd1371
Create Date: 2025-10-29 08:56:46.364613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85c1e7fa0e1'
down_revision: Union[str, Sequence[str], None] = '4c0aeefd1371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
